"architecture":
  "nodes":
  - !Component
    "attributes":
      "block_size": 32
      "datawidth": 8
      "depth": 8192
      "width": 512
      "word_bits": 8
    "class": "DRAM"
    "name": "MainMemory"
    "required_actions":
    - "read"
    - "write"
  - !Component
    "attributes":
      "block_size": 32
      "datawidth": 8
      "depth": 32
      "width": 32
      "word_bits": 8
    "class": "SRAM"
    "constraints":
      "dataspace":
        "bypass":
        - "Output"
        - "Output2"
    "name": "IntermediateBuffer"
    "required_actions":
    - "read"
    - "write"
  - !Container
    "attributes":
      "datawidth": 8
      "depth": 16
      "meshX": 8
      "meshY": 8
      "width": 16
    "name": "nnEngine"
    "spatial":
      "meshX": 8
      "meshY": 8
  - !Container
    "attributes":
      "datawidth": 8
      "depth": 8
      "meshX": 8
      "meshY": 8
      "width": 8
    "name": "PE"
    "spatial":
      "meshX": 8
      "meshY": 8
  - !Component
    "attributes":
      "datawidth": 8
      "depth": 128
      "width": 8
    "class": "smart_storage"
    "name": "scratchpad"
  - !Component
    "attributes":
      "datawidth": 8
      "depth": 16
      "width": 64
    "class": "regfile"
    "constraints":
      "dataspace":
        "bypass":
        - "Matrix_1"
        - "Matrix_2"
        - "Matrix_3"
        - "Matrix_4"
        - "OutputVector4"
        "keep":
        - "Input"
        - "OutputVector1"
        - "OutputVector2"
        - "OutputVector3"
    "name": "input_reg"
    "required_actions":
    - "read"
    - "write"
    - "compute"
  - !Component
    "attributes":
      "datawidth": 8
      "depth": 16
      "width": 64
    "class": "regfile"
    "constraints":
      "dataspace":
        "bypass":
        - "Matrix_1"
        - "Matrix_2"
        - "Matrix_3"
        - "Matrix_4"
        - "Input"
        "keep":
        - "OutputVector1"
        - "OutputVector2"
        - "OutputVector3"
        - "OutputVector4"
    "name": "output_reg"
    "required_actions":
    - "read"
    - "write"
    - "compute"
  - !Component
    "attributes":
      "datawidth": 8
      "depth": 16
      "width": 64
    "class": "regfile"
    "constraints":
      "dataspace":
        "bypass":
        - "Input"
        - "OutputVector1"
        - "OutputVector2"
        - "OutputVector3"
        - "OutputVector4"
        "keep":
        - "Matrix_1"
        - "Matrix_2"
        - "Matrix_3"
        - "Matrix_4"
    "name": "weights_reg"
    "required_actions":
    - "read"
    - "write"
    - "compute"
  - !Component
    "attributes":
      "cycle_time": "1e-9"
      "datawidth": 8
      "width": 8
    "class": "intmac"
    "name": "MACC"
    "required_actions":
    - "compute"
  "version": 0.4
"variables":
  "global_cycle_seconds": "1e-9"
  "technology": "45nm"
