architecture:
  version: 0.4
  nodes:
    - !Container
      name: system_arch
      attributes:
        # Top-level attributes inherited by all components unless overridden
        technology: "45nm"
        global_cycle_seconds: 1e-9
        datawidth: 16
      

    - !Component
      name: DRAM # offchip DRAM is the source of all datatypes
      class: DRAM # assume DRAM is large enough to store all the data, so no depth specification needed
      attributes:
        width: 64 # width in bits
        datawidth: 16
      required_actions: ['read', 'write']

    - !Container
      name: chip

    - !Container
      name: NNengine
      spatial: { meshX: 16, meshY: 16 }

    - !Component
      name: global_buffer
      class: SRAM
      attributes:
        width: 128
        depth: 2048
        datawidth: 16
        n_banks: 1
        n_rdwr_ports: 2
      required_actions: ['read', 'write']

    - !Container
      name: PE
      spatial: { meshX: 8, meshY: 8 }

    - !Component
      name: scratchpad
      class: SRAM # definitions of the compound classes can be found under "components" folder
      attributes:
        depth: 128
        width: 16
        datawidth: 16
      required_actions: ['read', 'write']

    # registers for the mac unit
    - !Component
      name: weight_reg
      class: regfile
      attributes: 
          depth: 1
          width: 16 
          datawidth: 16
      required_actions: ['read', 'write']

    - !Component
      name: input_activation_reg
      class: regfile
      attributes: 
          depth: 1
          width: 16 
          datawidth: 16
      required_actions: ['read', 'write']

    - !Component
      name: output_activation_reg
      class: regfile
      attributes: 
          depth: 1
          width: 16 
          datawidth: 16
      required_actions: ['read', 'write']

    - !Component
      name: mac
      class: intmac
      attributes: 
          num_pipline_stages: 2
          width: 16
          datawidth: 16 
      required_actions: ['compute']

