mapping:
  type: fused
  nodes:
    - type: storage
      target: 0 # CHRIS
      dspace: [Input, Filter_1, Output, Filter_2, Output2, Filter_3, Output3]
    - type: sequential
      branches:
        # corresponds to the b,o,i loop order on page 6
        # input rows, weight cols, input cols
        - - type: storage # CHRIS
            target: 1
            dspace: [Input, Filter_1]
          - type: temporal
            rank: N
            tile_shape: 1
          - type: storage
            target: 1
            dspace: [Output]
          - type: temporal
            rank: M
            tile_shape: 1
          - type: temporal
            rank: Q
            tile_shape: 1
          - type: temporal
            rank: P
            tile_shape: 1
          - type: temporal
            rank: C
            tile_shape: 1
          - type: temporal
            rank: R
            tile_shape: 1
          - type: temporal
            rank: S
            tile_shape: 1
          - type: compute
            einsum: Conv1
            target: 3 # CHRIS

        - - type: storage # CHRIS
            target: 1
            dspace: [Output, Filter_2]
          - type: temporal
            rank: N2
            tile_shape: 1
          - type: storage
            target: 1
            dspace: [Output2]
          - type: temporal
            rank: M2
            tile_shape: 1
          - type: temporal
            rank: Q2
            tile_shape: 1
          - type: temporal
            rank: P2
            tile_shape: 1
          - type: temporal
            rank: C2
            tile_shape: 1
          - type: temporal
            rank: R2
            tile_shape: 1
          - type: temporal
            rank: S2
            tile_shape: 1
          - type: compute
            einsum: Conv2
            target: 3 # CHRIS

        - - type: storage # CHRIS
            target: 1
            dspace: [Output2, Filter_3]
          - type: temporal
            rank: N3
            tile_shape: 1
          - type: storage
            target: 1
            dspace: [Output3]
          - type: temporal
            rank: M3
            tile_shape: 1
          - type: temporal
            rank: Q3
            tile_shape: 1
          - type: temporal
            rank: P3
            tile_shape: 1
          - type: temporal
            rank: C3
            tile_shape: 1
          - type: temporal
            rank: R3
            tile_shape: 1
          - type: temporal
            rank: S3
            tile_shape: 1
          - type: compute
            einsum: Conv3
            target: 3 # CHRIS

