# problem:
#   - shape:
#       name: Mul1
#       dimensions: [ A, B ]
#       data_spaces:
#       - name: InputVector
#         dimensions: [ IV_H, IV_W ]
#         projection: '[ B, A ]'
#       - name: Matrix_1
#         dimensions: [ M1_H, M1_W ]
#         projection: '[ A, A ]'
#       - name: OutputVector1
#         dimensions: [ O1V_H, O1V_W ]
#         projection: '[ B, A ]'
#         read_write: True

#     instance: >-
#       0 <= A < 128
