mapping:
  type: fused
  nodes:
  - type: storage
    target: 0  # CHRIS
    dspace: [Input, Filter_1, Output]
  - type: sequential  
    branches:
    # corresponds to the b,o,i loop order on page 6
    # input rows, weight cols, input cols
    - - type: storage # CHRIS 
        target: 1  
        dspace: [Input, Filter_1]
      - type: temporal 
        rank: N
        tile_shape: 1
      - type: storage 
        target: 1
        dspace: [Output]
      - type: temporal
        rank: M
        tile_shape: 1
      - type: temporal
        rank: Q
        tile_shape: 1
      - type: temporal
        rank: P
        tile_shape: 1
      - type: temporal
        rank: C
        tile_shape: 1
      - type: temporal
        rank: R
        tile_shape: 1
      - type: temporal
        rank: S
        tile_shape: 1
      - type: compute 
        einsum: Conv1
        target: 2  # CHRIS
    