"problem":
- "instance": "0 <= N < 1 and 0 <= M < 1 and 0 <= P <= 64 and 0 <= Q <= 64 and 0 <=\
    \ C < 1 and 0 <= R <= 1 and 0 <= S < 1"
  "shape":
    "data_spaces":
    - "dimensions":
      - "I_batches"
      - "I_Channels"
      - "I_Height"
      - "I_Width"
      "name": "Input"
      "projection": "[ N, C, P + R, Q + S]"
    - "dimensions":
      - "F_batches"
      - "F_channels"
      - "F_Height"
      - "F_Width"
      "name": "Filter_1"
      "projection": "[ M, C, R, S ]"
    - "dimensions":
      - "O_in_b"
      - "O_out_b"
      - "O_Height"
      - "O_Width"
      "name": "Output"
      "projection": "[ N, M, P, Q ]"
      "read_write": true
    "dimensions":
    - "C"
    - "M"
    - "R"
    - "S"
    - "N"
    - "P"
    - "Q"
    "name": "Conv1"
- "instance": "0 <= N2 < 1 and 0 <= M2 < 1 and 0 <= P2 <= 64 and 0 <= Q2 <= 64 and\
    \ 0 <= C2 < 1 and 0 <= R2 <= 1 and 0 <= S2"
  "shape":
    "data_spaces":
    - "dimensions":
      - "I_batches2"
      - "I_Channels2"
      - "I_Height2"
      - "I_Width2"
      "name": "Output"
      "projection": "[ N2, C2, P2 + R2, Q2 + S2]"
    - "dimensions":
      - "F_batches2"
      - "F_channels2"
      - "F_Height2"
      - "F_Width2"
      "name": "Filter_2"
      "projection": "[ M2, C2, R2, S2 ]"
    - "dimensions":
      - "O_in_b2"
      - "O_out_b2"
      - "O_Height2"
      - "O_Width2"
      "name": "Output2"
      "projection": "[ N2, M2, P2, Q2 ]"
      "read_write": true
    "dimensions":
    - "C2"
    - "M2"
    - "R2"
    - "S2"
    - "N2"
    - "P2"
    - "Q2"
    "name": "Conv2"
