"mapping":
  "nodes":
  - "dspace":
    - "Input"
    - "Filter_1"
    - "Filter_2"
    - "Output2"
    "target": 0
    "type": "storage"
  - "rank": "C2"
    "tile_shape": 32
    "type": "temporal"
  - "dspace":
    - "Output"
    "target": 1
    "type": "storage"
  - "branches":
    - - "rank": "M"
        "tile_shape": 1
        "type": "spatial"
      - "rank": "C"
        "tile_shape": 64
        "type": "spatial"
      - "dspace":
        - "Input"
        "target": 4
        "type": "storage"
      - "dspace":
        - "Filter_1"
        "target": 5
        "type": "storage"
      - "dspace":
        - "Output"
        "target": 6
        "type": "storage"
      - "rank": "Q"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "P"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "C"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "M"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "R"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "S"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "N"
        "tile_shape": 1
        "type": "temporal"
      - "einsum": "Conv1"
        "target": 3
        "type": "compute"
    - - "rank": "M2"
        "tile_shape": 64
        "type": "spatial"
      - "rank": "C2"
        "tile_shape": 1
        "type": "spatial"
      - "dspace":
        - "Output"
        "target": 4
        "type": "storage"
      - "dspace":
        - "Filter_2"
        "target": 5
        "type": "storage"
      - "dspace":
        - "Output2"
        "target": 6
        "type": "storage"
      - "rank": "M2"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "Q2"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "P2"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "C2"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "R2"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "S2"
        "tile_shape": 1
        "type": "temporal"
      - "rank": "N2"
        "tile_shape": 1
        "type": "temporal"
      - "einsum": "Conv2"
        "target": 3
        "type": "compute"
    "type": "pipeline"
  "type": "fused"
